inha-talktalk/TalkTalk

client/components/Button/index.tsx

Button 컴포넌트 작성

---

client/components/UserState/index.tsx

- #17
- User State 컴포넌트 작성
- 로그인 상태(props)에 따라 알아서 바뀌도록 구현

UserState 컴포넌트 작성

---

.github/workflows/client-ci.yml

- #21 
- Client CI 추가
- client 폴더에 변경이 있을 때만 검사하도록

Client CI 추가

---

.github/workflows/client-ci.yml

Client CI에서 캐싱을 하도록 수정

---

.github/workflows/server-ci.yml

server-ci 수정

---

.github/workflows/server-ci.yml

server-ci 설정 변경

---

client/components/MyAchievement/index.tsx
client/components/MyAchievementList/index.tsx
client/global.d.ts
client/pages/_app.tsx
client/pages/api/user/achievement/[userId].ts
client/pages/index.tsx
client/pages/selfStudy/index.tsx
client/utils/api.ts
client/utils/date.ts

- #44
- MyAchievement 작성
- MyAchievementList 작성
- `/user/achievement/:userId` mock API 작성
- Date 관련 함수 구현
- 모든 페이지 Top Padding 적용

Achievement 관련 컴포넌트 작성

---

client/components/StudyBanner/index.tsx
client/components/StudyCell/index.tsx
client/components/StudyCell/style.ts
client/global.d.ts
client/pages/api/self-study/[selfStudyId].ts
client/pages/api/self-study/list.ts
client/pages/selfStudy/index.tsx
client/utils/api.ts

- #52
- SelfStudyBanner 작성
- api `get`함수 작성
- self-study mock API 작성
- StudyCell 컴포넌트 작성
- 셀프 스터디 진입 페이지 마크업

FE 셀프 스터디 진입 페이지 마크업

---

client/pages/selfStudy/index.tsx

fix: StudyCell 마지막 css 적용

---

server/build.gradle
server/src/main/java/com/inha/server/ServerApplication.java
server/src/main/java/com/inha/server/mongodb/config/MongoDbConfig.java
server/src/main/java/com/inha/server/oauth/OAuthController.java
server/src/main/java/com/inha/server/oauth/OAuthService.java
server/src/main/java/com/inha/server/oauth/config/ClientConfig.java
server/src/main/java/com/inha/server/oauth/controller/OAuthController.java
server/src/main/java/com/inha/server/oauth/dto/JwtDto.java
server/src/main/java/com/inha/server/oauth/dto/OAuthUserDto.java
server/src/main/java/com/inha/server/oauth/dto/SocialUserDto.java
server/src/main/java/com/inha/server/oauth/model/ClientToken.java
server/src/main/java/com/inha/server/oauth/model/KakaoTokens.java
server/src/main/java/com/inha/server/oauth/service/OAuthService.java
server/src/main/java/com/inha/server/security/config/SecurityConfig.java
server/src/main/java/com/inha/server/security/exception/JwtAccessDeniedHandler.java
server/src/main/java/com/inha/server/security/exception/JwtAuthenticationEntryPoint.java
server/src/main/java/com/inha/server/security/jwt/JwtFilter.java
server/src/main/java/com/inha/server/security/jwt/JwtSecurityConfig.java
server/src/main/java/com/inha/server/security/jwt/TokenProvider.java
server/src/main/java/com/inha/server/user/model/User.java
server/src/main/java/com/inha/server/user/repository/UserRepository.java

- #54 
- spring security 설정
- access token으로 회원 정보 요청
- 회원 정보로 talktalk 서비스에 등록된 사용자인지 확인해서 등록되지 않은 사용자라면 회원가입
- 로그인
- jwt 발급
- Mongo db 연동 설정

Kakao Login, 회원가입

---

client/components/InputBar/index.tsx
client/components/TagInputBar/index.tsx
client/components/TagInputBar/style.ts
client/components/TextArea/index.tsx
client/components/TitleInputBar/index.tsx
client/package.json
client/pages/_app.tsx
client/pages/createStudyGroup/index.tsx
client/styles/calendar.css
client/yarn.lock

- #57
- TextArea 컴포넌트 작성
- TitleInputBar 컴포넌트 작성
- TagInputBar 컴포넌트 작성
- 스터디 그룹 생성 페이지 마크업

스터디 그룹 생성 페이지 마크업

---

server/src/main/java/com/inha/server/oauth/controller/OAuthController.java

- #66 
- OAuthController 의 kakaoLogin 메서드 Post 로 수정

:recycle: OAuthController 의 kakaoLogin 메서드 Post 로 수정

---

client/utils/api.ts

카카오 로그인 API POST 변경 적용

---

client/global.d.ts
client/pages/api/group-study/index.ts
client/pages/findStudyGroup/index.tsx
client/utils/api.ts

- #62 
- `/group-study?keyword={}&page={}` mock API 구현
- 스터디 그룹 검색 페이지 마크업

스터디 그룹 검색 페이지 마크업

---

client/pages/postView/index.tsx

- #70 
- 그룹 스터디 상세 페이지 마크업
- 추후 API와 연동 예정

그룹 스터디 상세 페이지 마크업

---

.github/workflows/server-ci.yml

hotfix: server CI 수정

---

server/src/main/java/com/inha/server/study/group/controller/GroupStudyController.java
server/src/main/java/com/inha/server/study/group/dto/response/DeleteGroupStudyRes.java
server/src/main/java/com/inha/server/study/group/dto/response/GetGroupStudyDetailRes.java
server/src/main/java/com/inha/server/study/group/service/GroupStudyService.java

- #83 
- 스터디 그룹 게시글 상세조회
- 스터디 종료

BE 스터디 그룹 게시글 상세조회, 스터디 종료

---

server/.gitignore
server/src/main/java/com/inha/server/mypage/controller/MayPageController.java
server/src/main/java/com/inha/server/mypage/dto/ProfileInfoRes.java
server/src/main/java/com/inha/server/mypage/dto/request/ProfileNameAndNicknameReq.java
server/src/main/java/com/inha/server/mypage/dto/response/ProfileInfoRes.java
server/src/main/java/com/inha/server/mypage/service/MyPageService.java
server/src/main/java/com/inha/server/oauth/dto/OAuthUserDto.java
server/src/main/java/com/inha/server/oauth/service/OAuthService.java
server/src/main/java/com/inha/server/user/model/User.java

- #64 
- 마이페이지 조회 dto 추가
- gitignore 파일에 application-prod.yml 파일 추가
- User 에 Builder 적용
- 마이페이지 조회 기능
- User 에서 name 과 nickname final 해제
- 프로필 이름 & 닉네임 수정 기능 추가

마이페이지 기능 구현 (1) 프로필

---

client/components/UserState/index.tsx
client/pages/oauth/kakao.tsx
client/states/login.ts

- #91
- 새로고침 시 로그인이 풀리던 문제 수정
- 로그아웃 기능 구현

로그인이 유지되지 않는 문제 수정

---

server/src/main/java/com/inha/server/mypage/controller/MyPageController.java
server/src/main/java/com/inha/server/mypage/service/MyPageService.java

- #64 
- jwt 없이 user 정보 조회 가능하도록, 에러 발생 시 404 응답하도록

jwt 없이 user 정보 조회 가능하도록, 에러 발생 시 404 응답하도록

---

server/src/main/java/com/inha/server/mypage/controller/MyPageController.java
server/src/main/java/com/inha/server/mypage/service/MyPageService.java

- #64 
- 회원 정보 조회를 Other(jwt 없음) 와 Self(jwt 있음) 로 분리
- 401 에러 반환 추가

회원 정보 조회 self 추가

---

server/src/main/java/com/inha/server/mypage/service/MyPageService.java

- #64 
- 다른 유저 정보 조회 성공시 404 -> 200 상태 반환

다른 유저 정보 조회 성공시 404 반환 오류 해결

---

server/src/main/java/com/inha/server/mypage/dto/request/ProfileNameAndNicknameReq.java

- #64 
- 프로필 닉네임 & 이름 수정 오류 해결

프로필 닉네임 & 이름 수정 오류 해결

---

server/src/main/java/com/inha/server/mypage/controller/MyPageController.java
server/src/main/java/com/inha/server/mypage/dto/response/AchievementRes.java
server/src/main/java/com/inha/server/mypage/dto/response/MyStudiesRes.java

- #98 
- 사용자 달성 현황 조회
- 사용자 완료 & 진행 & 신청 스터디 조회

마이페이지 Mock API 작성

---

server/src/main/java/com/inha/server/study/group/controller/GroupStudyController.java
server/src/main/java/com/inha/server/study/group/dto/response/PostGroupStudyAcceptRes.java
server/src/main/java/com/inha/server/study/group/dto/response/WaitingListRes.java
server/src/main/java/com/inha/server/study/group/model/GroupStudy.java
server/src/main/java/com/inha/server/study/group/service/GroupStudyService.java

- #87 
- 스터디 그룹 가입 신청
- 스터디 그룹 가입 신청 목록 조회
- 스터디 그룹 가입 수락

BE 스터디 그룹 가입 신청, 가입 신청 목록 조회, 가입 수락

---

server/build.gradle
server/src/main/java/com/inha/server/mypage/controller/MyPageController.java
server/src/main/java/com/inha/server/mypage/dto/response/ProfileInfoRes.java
server/src/main/java/com/inha/server/swagger/config/SwaggerConfig.java

- #103 
- Swagger 의존성 추가
- Swagger Config 추가
- MyPageController 일부 메서드 Swagger 적용

Swagger 적용

---

client/components/PostCell/index.tsx
client/global.d.ts
client/pages/api/group-study/[groupStudyId]/post.ts
client/pages/api/language.ts
client/pages/createStudyGroup/index.tsx
client/pages/postView/[groupStudyId].tsx
client/utils/api.ts

- #111
- 그룹 스터디 신청 페이지 API 연결
- 그룹 스터디 생성 페이지 API 연결

FE 그룹 스터디 생성, 그룹 스터디 신청 페이지 API 연결

---

server/src/main/java/com/inha/server/mypage/controller/MyPageController.java
server/src/main/java/com/inha/server/mypage/service/MyPageService.java
server/src/main/java/com/inha/server/study/group/model/ApplyStatus.java
server/src/main/java/com/inha/server/study/group/repository/ApplyStatusRepository.java
server/src/main/java/com/inha/server/study/group/service/GroupStudyService.java

- #107 
- ApplyStatus Collection 생성
- 스터디 신청 & 수락 시 ApplyStatus 생성 및 accepted 값 갱신되도록 GroupStudyService 로직 일부 수정
- GET /user/study/apply 기능 구현
- GET /user/study/{status} 기능 구현

마이페이지 기능 구현 (2) 스터디 목록

---

client/components/StudyCardList/index.tsx
client/global.d.ts
client/pages/myPage/index.tsx
client/utils/api.ts

- #115 
- 마이페이지 진행, 완료, 신청한 스터디 표시

FE 마이페이지 스터디 목록 연동

---

client/components/Modal/index.tsx
client/components/Modal/style.ts
client/components/SelfStudySharePanel/index.tsx
client/components/SelfStudySharePanel/style.ts

- #117 
- 모달 구현
- 셀프 스터디 공유 컴포넌트 구현

FE 셀프 스터디 공유 모달 구현

---

server/src/main/java/com/inha/server/chatGPT/config/OpenAIRestTemplateConfig.java
server/src/main/java/com/inha/server/chatGPT/controller/ChatController.java
server/src/main/java/com/inha/server/chatGPT/dto/Message.java
server/src/main/java/com/inha/server/chatGPT/dto/request/ChatReq.java
server/src/main/java/com/inha/server/chatGPT/dto/response/ChatRes.java

Chat GPT API 연동

---

server/src/main/java/com/inha/server/study/group/controller/GroupStudyController.java
server/src/main/java/com/inha/server/study/group/dto/request/PostGroupStudyReq.java
server/src/main/java/com/inha/server/study/group/dto/response/GetGroupStudyInfoRes.java
server/src/main/java/com/inha/server/study/group/dto/response/GetGroupStudyPostDetailRes.java
server/src/main/java/com/inha/server/study/group/dto/response/GroupStudyRes.java
server/src/main/java/com/inha/server/study/group/model/GroupStudy.java
server/src/main/java/com/inha/server/study/group/service/GroupStudyService.java

- #120 
- 스터디 기간 지정
- 스터디 state 필드 추가
- ongoing, done
- 스터디 정보 상세조회

BE 스터디 목록 조회, 게시글 상세조회, 스터디 정보 상세조회

---

server/src/main/java/com/inha/server/mypage/service/MyPageService.java
server/src/main/java/com/inha/server/study/group/repository/GroupStudyRepository.java

- #107 
- 사용자가 생성한 스터디도 스터디 목록에 추가되도록 수정

사용자가 생성한 스터디도 스터디 목록에 추가되도록 수정

---

server/src/main/java/com/inha/server/study/group/dto/request/PostGroupStudyReq.java
server/src/main/java/com/inha/server/study/group/model/GroupStudy.java
server/src/main/java/com/inha/server/study/group/service/GroupStudyService.java

BE 스터디 마감 기한 관련 오류 해결

---

server/src/main/java/com/inha/server/oauth/security/SecurityConfig.java

✨feat: CORS allow origin 추가

---

client/components/Button/index.tsx
client/components/ChatInputBar/index.tsx
client/components/InfoBanner/index.tsx
client/components/PostCell/index.tsx
client/components/SelfStudyController/index.tsx
client/components/SelfStudyPanel/index.tsx
client/components/SelfStudySharePanel/index.tsx
client/components/StudyCell/index.tsx
client/components/TagInputBar/index.tsx
client/components/TextArea/index.tsx
client/pages/api/group-study/index.ts
client/pages/createStudyGroup/index.tsx
client/pages/index.tsx
client/pages/selfStudy/index.tsx
client/pages/selfStudy/read.tsx
client/pages/selfStudy/view/read.tsx
client/pages/selfStudy/view/write.tsx
client/pages/selfStudy/write.tsx
client/utils/date.ts

- #122 
- SelfStudyController, InfoBanner 이미 완료된 스터디 지원
- 셀프 스터디 조회 페이지 마크업
- 여러 컴포넌트 리랜더링 최적화

FE 셀프 스터디 조회 페이지 구현 및 최적화

---

.github/workflows/server-ci.yml

fix: application.yml 제거 적용

---

server/.gitignore
server/src/main/resources/application.yml

gitignore 에 application.yml 추가

---

client/components/GroupStudyController/GroupStudySetting/index.tsx
client/components/GroupStudyController/GroupStudySetting/style.ts
client/components/GroupStudyController/GroupStudySettingController/index.tsx
client/components/UserSlot/index.tsx
client/styles/globals.css

- #149 
- GroupStudySetting 컴포넌트 작성
- UserSlot disable hover 옵션 추가
- global scroll bar 스타일 수정

FE 그룹스터디 설정 모달 마크업

---

server/src/main/java/com/inha/server/study/group/controller/GroupStudyController.java
server/src/main/java/com/inha/server/study/group/service/GroupStudyService.java

- #155 
- Response Entity 적용
- 예외처리 추가

BE API 예외처리 로직 추가

---

server/src/main/java/com/inha/server/language/controller/LanguageController.java
server/src/main/java/com/inha/server/language/dto/response/ScriptTypeDto.java
server/src/main/java/com/inha/server/swagger/config/SwaggerConfig.java

- #158 
- GET /scriptType API 구현
- Swagger 업데이트

스크립트 타입 제공 API 추가 & Swagger Contorller 추가

---

client/components/CreateSelfStudy/index.tsx
client/package.json
client/pages/_app.tsx
client/pages/createStudyGroup/index.tsx
client/pages/myPage/index.tsx
client/pages/oauth/kakao.tsx
client/pages/postView/[groupStudyId].tsx
client/yarn.lock

FE react-toast 적용

---

client/components/CreateSelfStudy/index.tsx
client/components/StudyCardList/index.tsx
client/global.d.ts
client/pages/findStudyGroup/index.tsx
client/utils/api.ts

- #163
- `GET /scriptType` API 적용
- key prop 관련 버그 수정

스크립트 타입 API 연동 및 버그 수정

---

server/src/main/java/com/inha/server/study/group/service/GroupStudyService.java

BE response status code 수정

---

server/src/main/java/com/inha/server/chatGPT/controller/ChatController.java
server/src/main/java/com/inha/server/chatGPT/model/Script.java
server/src/main/java/com/inha/server/chatGPT/repository/ScriptRepository.java
server/src/main/java/com/inha/server/chatGPT/service/ScriptService.java
server/src/main/java/com/inha/server/study/self/controller/SelfStudyController.java
server/src/main/java/com/inha/server/study/self/dto/reponse/ScriptDto.java
server/src/main/java/com/inha/server/study/self/service/SelfStudyService.java
server/src/main/java/com/inha/server/user/model/UserScriptList.java
server/src/main/java/com/inha/server/user/repository/UserScriptRepository.java

- #169 
- Script Document 에 language 추가
- UserScriptList Document 추가
-  /self-study?languageId={}&type={} API 구현

BE 스터디 생성 API 구현

---

server/src/main/java/com/inha/server/chatGPT/controller/ChatController.java
server/src/main/java/com/inha/server/chatGPT/dto/request/ScriptReq.java
server/src/main/java/com/inha/server/language/controller/LanguageController.java

- #169 
- /chat API 파라미터 방식 수정
- /script-type API 명 수정

API 일부 명명 수정

---

client/utils/api.ts

🚑 hotfix: 스크립트 타입 API 경로 수정

---

server/src/main/java/com/inha/server/study/group/controller/GroupStudyController.java

- #179 
- 
- JWT가 없어도 실행되도록 수정

BE hotfix 그룹 스터디 리스트 조회, 검색 API 수정

---

server/src/main/java/com/inha/server/language/enumtype/language.java

stt, tts 언어 목록 업데이트

---

server/src/main/java/com/inha/server/language/dto/response/LanguageDto.java
server/src/main/java/com/inha/server/language/service/LanguageService.java

- #184 
- /language 호출 시 tts, stt 값도 넘겨주도록

/language 호출 시 tts, stt 값도 넘겨주도록

---

server/src/main/java/com/inha/server/oauth/security/SecurityConfig.java

CORS DELETE 추가

---

server/build.gradle
server/src/main/java/com/inha/server/mongodb/config/MongoDbConfig.java
server/src/main/java/com/inha/server/mongodb/config/ReactiveMongoDbConfig.java
server/src/main/java/com/inha/server/study/group/controller/GeneralChatController.java
server/src/main/java/com/inha/server/study/group/dto/request/PostGeneralChatReq.java
server/src/main/java/com/inha/server/study/group/model/GeneralChat.java
server/src/main/java/com/inha/server/study/group/model/GeneralContent.java
server/src/main/java/com/inha/server/study/group/repository/GeneralChatRepository.java
server/src/main/java/com/inha/server/study/group/service/ChatService.java

BE 그룹 스터디 일반 채팅

---

server/src/main/java/com/inha/server/study/self/dto/request/EndSelfStudyWriteReq.java
server/src/main/java/com/inha/server/study/self/model/SelfStudy.java

- #169 
- 셀프 스터디 쓰기 데이터 전송 & 반환 형태 단순 문자열 배열로 수정

셀프 스터디 쓰기 데이터 전송 & 반환 형태 수정

---

server/src/main/java/com/inha/server/study/self/model/SelfStudy.java
server/src/main/java/com/inha/server/study/self/service/SelfStudyService.java

- #169 
- SelfStudy Document 에 isFinished 컬럼 추가
- 스터디 삭제 시 isFinished 값을 확인하여 종료된 스터디일 경우 403 에러 반환

완료된 셀프 스터디는 삭제하지 못하도록 수정

---

server/src/main/java/com/inha/server/mypage/controller/MyPageController.java
server/src/main/java/com/inha/server/mypage/dto/response/AchievementRes.java
server/src/main/java/com/inha/server/mypage/service/MyPageService.java
server/src/main/java/com/inha/server/oauth/service/OAuthService.java
server/src/main/java/com/inha/server/study/self/model/SelfStudy.java
server/src/main/java/com/inha/server/study/self/repository/SelfStudyRepository.java
server/src/main/java/com/inha/server/study/self/service/SelfStudyService.java
server/src/main/java/com/inha/server/user/model/User.java
server/src/main/java/com/inha/server/user/service/UserService.java

- #186 
- User Document 의 joinTime 타입을 String 으로 변경
- User Document 에 languageList 추가
- 회원가입 과정에서 User 객체 생성 시 ISO 타입으로 가입날짜 추가되도록
- Script Document 에 languageId 추가
- GET /user/achieve API 구현

GET /user/achieve API 구현

---

server/build.gradle
server/src/main/java/com/inha/server/study/self/controller/SelfStudyController.java
server/src/main/java/com/inha/server/study/self/dto/request/EndSelfStudyReadReq.java
server/src/main/java/com/inha/server/study/self/service/SelfStudyService.java

- #169 
- POST /self-study/read API 재구현

POST /self-study/read API 재구현

---

server/src/main/java/com/inha/server/study/self/controller/SelfStudyController.java
server/src/main/java/com/inha/server/study/self/dto/reponse/SelfStudyGetRes.java
server/src/main/java/com/inha/server/study/self/service/SelfStudyService.java

- #183 
- GET /self-study/{selfStudyId} API 구현

GET /self-study/{selfStudyId} API 구현

---

server/src/main/java/com/inha/server/study/group/service/GroupStudyService.java

BE hotfix 그룹 스터디 페이징 처리 수정

---

client/components/EventListener/index.tsx
client/pages/_app.tsx
client/utils/api.ts

- #110
- 로그인 만료시
- jwt state에서 제거
- localStorage에서 제거
- Axios Instance에서 제거
- tost 띄우기

로그인 인증 만료시 처리

---

client/pages/createStudyGroup/index.tsx
client/pages/findStudyGroup/index.tsx
client/pages/index.tsx
client/pages/myPage/index.tsx
client/pages/postView/[groupStudyId].tsx
client/pages/selfStudy/create/read.tsx
client/pages/selfStudy/create/write.tsx
client/pages/selfStudy/index.tsx
client/pages/selfStudy/read.tsx
client/pages/selfStudy/view/read.tsx
client/pages/selfStudy/view/write.tsx
client/pages/selfStudy/write.tsx
client/pages/studyGroup/[groupId].tsx
client/pages/studyGroup/index.tsx

모든 페이지에 title 지정

---

client/components/GroupStudyController/GroupStudySetting/OwnerSetting/index.tsx
client/components/GroupStudyController/GroupStudySetting/OwnerSetting/style.ts
client/components/GroupStudyController/GroupStudySetting/index.tsx
client/components/GroupStudyController/GroupStudySetting/style.ts
client/components/GroupStudyController/index.tsx
client/global.d.ts
client/pages/studyGroup/[groupId].tsx
client/utils/api.ts

- #206
- 그룹 스터디 수락 관련 API 추가
- 그룹 스터디 수락 컴포넌트 작성
- 스터디 설정에서 관리자 설정 컴포넌트 분리

FE 그룹 스터디 수락 컴포넌트 작성 및 적용

---

server/src/main/java/com/inha/server/study/group/controller/GroupStudyController.java

- #203 
- Controller 단에서 JWT 만료 시 예외처리

BE JWT 만료시 예외처리

---

server/src/main/java/com/inha/server/study/group/controller/GroupStudyController.java
server/src/main/java/com/inha/server/study/group/dto/response/GetSelfStudySharedListRes.java
server/src/main/java/com/inha/server/study/group/service/GroupStudyService.java
server/src/main/java/com/inha/server/study/self/controller/SelfStudyController.java
server/src/main/java/com/inha/server/study/self/model/SelfStudyShare.java
server/src/main/java/com/inha/server/study/self/repository/SelfStudyShareRepository.java
server/src/main/java/com/inha/server/study/self/service/SelfStudyService.java

- #213 
- POST /self-study/:selfStudyId?to=groupId 구현
- GET /group-study/:groupStudyId/share-chat 구현

BE 셀프 스터디 공유 기능 구현

---

server/src/main/java/com/inha/server/study/group/controller/GeneralChatController.java
server/src/main/java/com/inha/server/study/group/service/ChatService.java

BE hotfix 그룹 스터디 일반 채팅 조회 수정

---

server/src/main/java/com/inha/server/study/group/service/ChatService.java

BE hotfix 그룹 스터디 일반 채팅 조회 예외처리

---

server/src/main/java/com/inha/server/study/self/model/SelfStudyShare.java
server/src/main/java/com/inha/server/study/self/service/SelfStudyService.java

- #213 
- 전달 데이터에 StudyType 추가

전달 데이터에 StudyType 추가

---

server/src/main/java/com/inha/server/study/group/service/ChatService.java

일반 채팅 내역 조회 엣지 케이스 예외처리 추가

---

client/components/GroupStudyChat/ChatSlot/index.tsx
client/components/GroupStudyChat/index.tsx
client/components/SelfStudyController/index.tsx
client/components/SelfStudySharePanel/index.tsx
client/global.d.ts
client/states/groupStudy.ts
client/utils/api.ts
client/utils/date.ts

- #191
- 채팅 슬롯 수정
- 공유 채팅 구현
- 일반 채팅 구현

FE 채팅 기능 구현

---

client/components/SelfStudyController/index.tsx
client/components/SelfStudySharePanel/index.tsx
client/states/groupStudy.ts

- #191
- 기본 선택 채널 수정
- 셀프 스터디 공유 후 모달 닫히도록 수정

FE 모달 안닫히는 문제 및 기본 선택 채널 수정
